chain:
  ethereum:
    url: ""
depot:
  delay: 5
  host: "depot"
  port: 5002
log:
  level: "info"
  path: "./nym-dev.log"
metrics:
  host: "elasticsearch"
  port: 9200
nym:
  delay: 5
  host: "nym"
  port: 5001
postgres:
  host: "localhost"
  port: 5432
  name: "nym-dev"
  user: "user"
  pass: "SomePassword456"
  ssl: false
  tz: "UTC"
redis:
  host: "localhost"
  port: 6379
  pass: "SomePassword456"
sdk:
  depot: "http://localhost:5002"
  nym: "http://localhost:5001"
wallet:
  path: "./dome-wallet.dat"
